### ISSUE TITLE
TypeError: db.runCommand is not a function

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [seppevs/migrate-mongo#429] opened 2023-03-21 10:37 UTC
I get this error when trying to run this script:
```
await db.runCommand({
                    collMod: 'users',
                    validator: {
                        $jsonSchema: {
                            bsonType: 'object',
                            properties: {
                                details: {
                                    bsonType: 'object',
                                    properties: {
                                        type: {
                                            enum: ['valueOne', 'valueTwo'],
                                            description: 'Can only be one of the enum values',
                                        },
                                    },
                                },
                            },
                        },
                    },
                });
```

**Comment by vytautas-pranskunas-** [comment] 2023-04-11 08:18
is this project still supporte? because no response for 3 weeks...

**Comment by seppevs** [comment] 2023-09-27 07:41
Try to install the latest mongodb version in your project. The issue is not caused by migrate-mongo, so I'm closing this.

**Closed by seppevs** 2023-09-27 07:41 UTC

**Comment by vytautas-pranskunas-** [comment] 2023-09-27 07:44
If i am running this command via mongodb shell all works good. It is failing only once run via migrate mongo.

**Comment by seppevs** [comment] 2023-09-27 07:46
migrate-mongo is just a wrapper project around the mongodb node.js dependency. I suggest to see which version of `mongodb` is installed in your migration project.

**Comment by marxxxx** [comment] 2024-04-26 07:53
@vytautas-pranskunas- In case this is still relevant. I was receiving the same error but was able to solve it by calling `db.command() `instead of `db.runCommand()`. The parameters are the same.

 This SO-Thread was pointing me in the right direction: https://stackoverflow.com/questions/49765120/node-mongo-db-runcommand-is-not-a-function
