### ISSUE TITLE
MongoError: WriteConflict at Connection.

### ISSUE THREAD

**Issue by SuneelRealogyCode** [seppevs/migrate-mongo#364] opened 2021-05-26 13:04 UTC
**Describe the bug**
MongoError: WriteConflict at Connection.<anonymous> (/app/node_modules/migrate-mongo/node_modules/mongodb/lib/core/connection/pool.js:454:61) 
at Connection.emit (events.js:314:20) at Connection.EventEmitter.emit (domain.js:483:12)
at processMessage (/app/node_modules/migrate-mongo/node_modules/mongodb/lib/core/connection/connection.js:368:10) 
at TLSSocket.<anonymous> (/app/node_modules/migrate-mongo/node_modules/mongodb/lib/core/connection/connection.js:537:15) 
at TLSSocket.emit (events.js:314:20) at TLSSocket.EventEmitter.emit (domain.js:483:12) 
at addChunk (_stream_readable.js:298:12) at readableAddChunk (_stream_readable.js:273:9) 
at TLSSocket.Readable.push (_stream_readable.js:214:10) 
at TLSWrap.onStreamRead (internal/stream_base_commons.js:188:23) 
at TLSWrap.callbackTrampoline (internal/async_hooks.js:126:14) 
{ errorLabels: [ 'TransientTransactionError' ], 
operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1622001232 }, ok: 0, 
errmsg: 'WriteConflict', code: 112, codeName: 'WriteConflict', '$clusterTime': { clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1622001251 }, signature: { hash: [Binary], keyId: [Long] } }, [Symbol(mongoErrorContextSymbol)]: {} }\"}\n"

**To Reproduce**

**Expected behavior**

**Additional context**
Not sure why we are seeing this. Earlier we did not see this connection issue.

**Comment by seppevs** [comment] 2023-09-27 07:25
Issue does not seem to be caused by migrate-mongo, but on network / mongodb level? I'm closing this.

**Closed by seppevs** 2023-09-27 07:25 UTC
