### ISSUE TITLE
Migrate mongo 8.2.3 unable to connect to mongodb

### ISSUE THREAD

**Issue by krtk6160** [seppevs/migrate-mongo#398] opened 2021-09-28 09:39 UTC
**Describe the bug**
When I run `migrate-mongo status` on v8.2.3 while port-forwarding a kubectl mongodb pod I get this error ->
```
ERROR: getaddrinfo ENOTFOUND mongodb-0.mongodb-headless.mainnet.svc.cluster.local MongoServerSelectionError: getaddrinfo ENOTFOUND mongodb-0.mongodb-headless.mainnet.svc.cluster.local
at Timeout._onTimeout (/home/krtk6160/.nvm/versions/node/v14.17.3/lib/node_modules/migrate-mongo/node_modules/mongodb/lib/sdam/topology.js:325:38)
at listOnTimeout (internal/timers.js:557:17)
at processTimers (internal/timers.js:500:7)
```

However, doing the same on v8.2.2, I get the correct list of migrations I've already performed.

**To Reproduce**
- Run `kubectl port-forward mongodb-0 27017`
- Run `migrate-mongo status` in an already initialized directory

**Expected behavior**
I expect it to display my migrations correctly, just like v8.2.2 does.

**Comment by maxcian** [comment] 2021-11-12 08:18
same issue when I use 8.2.3 to connection localhost:27017 (e.g. run `migrate-mongo status `)

but use 8.2.2 is working correctly

**Comment by Jay-Funk** [comment] 2022-04-08 20:57
issue still exists in 9.0.0

**Comment by pflima92** [comment] 2022-06-28 20:06
Thanks @Jay-Funk, `directConnection` worked as a workaround.

**Comment by seppevs** [comment] 2023-09-27 07:28
See last comment for a workaround. Issue is not directly caused by migrate-mongo, so I'm closing this.

**Closed by seppevs** 2023-09-27 07:28 UTC
