### ISSUE TITLE
How to get the client connection?

### ISSUE THREAD

**Issue by XavierJordaMurria** [seppevs/migrate-mongo#105] opened 2019-09-19 11:24 UTC
It would be really interesting to use mongo transactions in your migration module, so if the migration can not fail half-way in. 

**Describe the solution you'd like**
Besides of getting the db connection to a mongo db as a param in the migration files up(db) or down(db), it would be great to have the MongoClient connection too.

Is it possible to do this alreay? Or would you consider to add it?

Thank you

**Comment by DanielRuf** [comment] 2019-10-02 18:28
It's not directly possible but you can use the same logic to create (and reuse) the client.

https://github.com/seppevs/migrate-mongo/blob/master/lib/env/database.js#L23

**Comment by DanielRuf** [comment] 2019-10-02 18:31
Possible duplicate of https://github.com/seppevs/migrate-mongo/issues/48

**Comment by seppevs** [comment] 2019-11-03 20:26
This is now possible in migrate-mongo 7.x.x or higher. Each migration gets now a `db` AND `client` argument. This last argument, `client`, is an instance of [MongoClient](https://mongodb.github.io/node-mongodb-native/3.3/api/MongoClient.html). See the README for more details.
Closing this ...

**Closed by seppevs** 2019-11-03 20:26 UTC
