### ISSUE TITLE
Transactions with migrate-mongo

### ISSUE THREAD

**Issue by mushketyk** [seppevs/migrate-mongo#48] opened 2019-04-25 17:31 UTC
**Is your feature request related to a problem? Please describe.**
It seems that at the moment it is no possible to use cross-document transactions using `migrate-mongo`.

`up` and `down` functions accept a single parameter `db` which is an instance of the [Db](http://mongodb.github.io/node-mongodb-native/3.1/api/Db.html) class. But to start a transaction we need to call the [startSession](http://mongodb.github.io/node-mongodb-native/3.1/api/MongoClient.html#startSession) method on the [MongoClient](http://mongodb.github.io/node-mongodb-native/3.1/api/MongoClient.html) class.

**Describe the solution you'd like**

Not sure what would be the best solution, but maybe `up` and `down` methods could receive two parameters: `(db, client)`

**Describe alternatives you've considered**
There does not seem to be a comprehensive alternative solution.

**Comment by Stradivario** [comment] 2019-07-26 09:20
Hi @mushketyk since it takes a lot of time to fix something inside the community it is always better to think about your use case and fight for it!

Basically what i am saying is that i am waiting your issue to be resolved from the first day that you write it April 25. Thus till that moment nobody even try to explain anything. Basically you are stuck with this situation! (open source community)

Before 2 days i decided to create my own migration library written in `typescript` with the following features in mind:

## Features

* Rollback support
* Typescript/Javascript compatible
* Simple UI/UX
* Templates for migrations
* Mongoose and Mongodb compatability
* Infinite Error log with `append` nodejs streaming technique
* `error` and `success` logs for `up`/`down` migrations 
* `async`/`await` configuration loader

You can find the lib here: https://github.com/rxdi/xmigrate

@mushketyk regards!

**Comment by DanielRuf** [comment] 2019-10-02 18:31
Hi @Stradivario,

Can you provide a PR for this in migrate-mongo?

**Comment by seppevs** [comment] 2019-11-03 20:24
Good news! I added support for the MongoDB Transaction API in migrate-mongo 7.x.x or higher.
See the README for all details! 

Closing this.

**Closed by seppevs** 2019-11-03 20:24 UTC

**Comment by DocAmaroo** [comment] 2022-12-21 13:03
In case, people come here with troubles, I was having issues to make the transactions, even by mocking the example provided on the [README](../blob/master/README.md#using-mongodbs-transactions-api).

I suddenly remembered that the session needs to be provided in the query options, and it worked has intended.

**For example**

In the query above (take out from the README):

```ts
await db.collection('albums').updateOne({artist: 'The Beatles'}, {$set: {blacklisted: true}});
```

The request should be updated like this:

```ts
await db.collection('albums').updateOne({artist: 'The Beatles'}, {$set: {blacklisted: true}}, { session });
// or
await db.collection('albums').updateOne({artist: 'The Beatles'}, {$set: {blacklisted: true}}, { session: session });
```

**System information**

- MongoDB 5.0.13

**Suggestion**

I think, it would be great to update the example on the README to avoid any further issues like this.
