### ISSUE TITLE
BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'

### ISSUE THREAD

**Issue by priyank6796** [seppevs/migrate-mongo#204] opened 2020-05-04 13:22 UTC
**Describe the bug**
I am trying to update my collection using mongo update query with aggregation which is supported by Mongo version 4.0 and higher. I tried to run the migration using this tool but I have got the error 

> ERROR: Could not migrate down 20200504124656-remove_deleted_messsage.js: BSON field 'update.updates.u' is the wrong type 'array', expected type 'object'

**Migration script** 
```
module.exports = {
  async up(db, client) {
	await db.collection('messages').updateMany(
		{ is_deleted: true, archived: { $exists: false } },
		[
			{"$set": {"archived.content": "$content", "archived.url": "$url"}},
			{"$unset": ["content", "url"]  }
		])
  },

  async down(db, client) {

  }
};
```

**To Reproduce**
- Create new migration with above script 
- Run migrate up command to reproduce the error

**Expected behavior**
- As suggested in mongoDB document. We can use aggregation pipeline with update query

![image](https://user-images.githubusercontent.com/17333370/80970059-36fbb600-8e38-11ea-955c-4932217a0359.png)

**Additional context**
I am able to run the same script from mongo client shell. But gives error with migration tool

**Comment by seppevs** [comment] 2020-05-08 10:06
I cannot reproduce this. I followed exactly the steps you mentioned.
Do you run ```migrate-mongo up``` with the CLI?

If not: just a wild guess, but are you using the migrate-mongo API in a TypeScript project? It might be an issue with the [migrate-mongo types](https://www.npmjs.com/package/@types/migrate-mongo) provided by the [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/migrate-mongo) project. This is not something I maintain.

**Comment by jamesholcomb** [comment] 2020-05-15 14:59
Updates with aggregation pipeline is a 4.2 feature:

https://docs.mongodb.com/manual/tutorial/update-documents-with-aggregation-pipeline/

**Comment by seppevs** [comment] 2020-07-21 06:46
I received no replies from OP, so I'm closing this. Please feel free to reopen when necessary.

**Closed by seppevs** 2020-07-21 06:46 UTC
